// <auto-generated />
using System;
using Fidlle.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fidlle.Infrastructure.Migrations.Skills
{
    [DbContext(typeof(SkillsContext))]
    [Migration("20250308131722_InitDefaultSkills")]
    partial class InitDefaultSkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fidlle.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Increases your physical power.",
                            MaxLevel = 30,
                            Name = "Strength"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Improves your resistance to damage.",
                            MaxLevel = 30,
                            Name = "Defence"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Determines your health capacity.",
                            MaxLevel = 30,
                            Name = "Hitpoints"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Enhances close combat efficiency.",
                            MaxLevel = 30,
                            Name = "Melee"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Improves ranged weapon accuracy and damage.",
                            MaxLevel = 30,
                            Name = "Ranged"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Improves your spellcasting abilities.",
                            MaxLevel = 30,
                            Name = "Magic"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Increases proficiency in ceremonial practices.",
                            MaxLevel = 30,
                            Name = "Rituals"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "Enhances ability to carve mystical runes.",
                            MaxLevel = 30,
                            Name = "Rune Carving"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Description = "Improves potion-making and transmutation skills.",
                            MaxLevel = 30,
                            Name = "Alchemy"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Increases proficiency in writing magical scrolls.",
                            MaxLevel = 30,
                            Name = "Scrolls Writing"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Description = "Improves the ability to summon creatures or entities.",
                            MaxLevel = 30,
                            Name = "Summoning"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Description = "Enhances crafting of weapons and armor.",
                            MaxLevel = 30,
                            Name = "Smithing"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Description = "Improves culinary skills and crafting food.",
                            MaxLevel = 30,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Description = "Increases proficiency in crafting wooden items.",
                            MaxLevel = 30,
                            Name = "Woodworking"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Description = "Improves crafting of fabric-based items.",
                            MaxLevel = 30,
                            Name = "Tailoring"
                        },
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101010"),
                            Description = "Enhances crafting of leather-based items.",
                            MaxLevel = 30,
                            Name = "Leatherworking"
                        },
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202020"),
                            Description = "Increases efficiency in cutting trees and gathering wood.",
                            MaxLevel = 30,
                            Name = "Woodcutting"
                        },
                        new
                        {
                            Id = new Guid("30303030-3030-3030-3030-303030303030"),
                            Description = "Enhances gathering and utilization of herbs.",
                            MaxLevel = 30,
                            Name = "Herbalism"
                        },
                        new
                        {
                            Id = new Guid("40404040-4040-4040-4040-404040404040"),
                            Description = "Improves proficiency in extracting ores and minerals.",
                            MaxLevel = 30,
                            Name = "Mining"
                        },
                        new
                        {
                            Id = new Guid("50505050-5050-5050-5050-505050505050"),
                            Description = "Allows gathering of resources from animals.",
                            MaxLevel = 30,
                            Name = "Skinning"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
